name: Update The Planet

on:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# allow these jobs to commit to the repository
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v2-beta
      with:
        ref: main

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up git repository
      run: |
        git status
        git branch

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update The Planet
      run: make

    - name: Commit changes
      run: |
        git diff
        git add docs
        ( git commit -m 'Updating the Planet via GitHub Actions' && git push origin main ) || echo 'Nothing to commit'
